package Models

import "time"

type Product struct {
	Products []Detail `json:"products,omitempty"`
}

type Detail struct {
	ID          int64         `json:"id,omitempty"`
	Title       string        `json:"title,omitempty"`
	Handle      string        `json:"handle,omitempty"`
	BodyHTML    string        `json:"body_html,omitempty"`
	PublishedAt time.Time     `json:"published_at,omitempty"`
	CreatedAt   time.Time     `json:"created_at,omitempty"`
	UpdatedAt   time.Time     `json:"updated_at,omitempty"`
	Vendor      string        `json:"vendor,omitempty"`
	ProductType string        `json:"product_type,omitempty"`
	Tags        []interface{} `json:"tags,omitempty"`
	Variants    []Variants    `json:"variants,omitempty"`
	Images      []Image       `json:"images,omitempty"`
	Options     []Options     `json:"options,omitempty"`
}

type Variants struct {
	ID               int64       `json:"id,omitempty"`
	Title            string      `json:"title,omitempty"`
	Option1          string      `json:"option1,omitempty"`
	Option2          interface{} `json:"option2,omitempty"`
	Option3          interface{} `json:"option3,omitempty"`
	Sku              string      `json:"sku,omitempty"`
	RequiresShipping bool        `json:"requires_shipping,omitempty"`
	Taxable          bool        `json:"taxable,omitempty"`
	FeaturedImage    interface{} `json:"featured_image,omitempty"`
	Available        bool        `json:"available,omitempty"`
	Price            string      `json:"price,omitempty"`
	Grams            int         `json:"grams,omitempty"`
	CompareAtPrice   interface{} `json:"compare_at_price,omitempty"`
	Position         int         `json:"position,omitempty"`
	ProductID        int64       `json:"product_id,omitempty"`
	CreatedAt        time.Time   `json:"created_at,omitempty"`
	UpdatedAt        time.Time   `json:"updated_at,omitempty"`
}

type Image struct {
	ID         int64         `json:"id,omitempty"`
	CreatedAt  time.Time     `json:"created_at,omitempty"`
	Position   int           `json:"position,omitempty"`
	UpdatedAt  time.Time     `json:"updated_at,omitempty"`
	ProductID  int64         `json:"product_id,omitempty"`
	VariantIds []interface{} `json:"variant_ids,omitempty"`
	Src        string        `json:"src,omitempty"`
	Width      int           `json:"width,omitempty"`
	Height     int           `json:"height,omitempty"`
}

type Options struct {
	Name     string   `json:"name,omitempty"`
	Position int      `json:"position,omitempty"`
	Values   []string `json:"values,omitempty"`
}

type AutoGenerated struct {
	Products []struct {
		ID          int64         `json:"id,omitempty"`
		Title       string        `json:"title,omitempty"`
		Handle      string        `json:"handle,omitempty"`
		BodyHTML    string        `json:"body_html,omitempty"`
		PublishedAt time.Time     `json:"published_at,omitempty"`
		CreatedAt   time.Time     `json:"created_at,omitempty"`
		UpdatedAt   time.Time     `json:"updated_at,omitempty"`
		Vendor      string        `json:"vendor,omitempty"`
		ProductType string        `json:"product_type,omitempty"`
		Tags        []interface{} `json:"tags,omitempty"`
		Variants    []struct {
			ID               int64       `json:"id,omitempty"`
			Title            string      `json:"title,omitempty"`
			Option1          string      `json:"option1,omitempty"`
			Option2          interface{} `json:"option2,omitempty"`
			Option3          interface{} `json:"option3,omitempty"`
			Sku              string      `json:"sku,omitempty"`
			RequiresShipping bool        `json:"requires_shipping,omitempty"`
			Taxable          bool        `json:"taxable,omitempty"`
			FeaturedImage    interface{} `json:"featured_image,omitempty"`
			Available        bool        `json:"available,omitempty"`
			Price            string      `json:"price,omitempty"`
			Grams            int         `json:"grams,omitempty"`
			CompareAtPrice   interface{} `json:"compare_at_price,omitempty"`
			Position         int         `json:"position,omitempty"`
			ProductID        int64       `json:"product_id,omitempty"`
			CreatedAt        time.Time   `json:"created_at,omitempty"`
			UpdatedAt        time.Time   `json:"updated_at,omitempty"`
		} `json:"variants,omitempty"`
		Images []struct {
			ID         int64         `json:"id,omitempty"`
			CreatedAt  time.Time     `json:"created_at,omitempty"`
			Position   int           `json:"position,omitempty"`
			UpdatedAt  time.Time     `json:"updated_at,omitempty"`
			ProductID  int64         `json:"product_id,omitempty"`
			VariantIds []interface{} `json:"variant_ids,omitempty"`
			Src        string        `json:"src,omitempty"`
			Width      int           `json:"width,omitempty"`
			Height     int           `json:"height,omitempty"`
		} `json:"images,omitempty"`
		Options []struct {
			Name     string   `json:"name,omitempty"`
			Position int      `json:"position,omitempty"`
			Values   []string `json:"values,omitempty"`
		} `json:"options,omitempty"`
	} `json:"products,omitempty"`
}
